// Edge Function: lead-upsert
// Runtime:  Supabase Edge (Deno)
// Purpose:  Single write-path for CLP leads + consent. Service-role-key lives
//           here (server-side env vars), never in the browser bundle.
//
// Endpoint shape:
//   POST  https://<project>.supabase.co/functions/v1/lead-upsert
//   Headers:
//     Content-Type: application/json
//     Authorization: Bearer <SUPABASE_ANON_KEY>
//   Body:
//     { "session_id": "...", "source": "clp_dehofman", ...lead fields,
//       "consents": [{ "scope": "...", "granted": true, "detail": {...} }] }
//
// Response: { ok: true, lead_id, portal_token, consents_inserted }
//
// Portal token: generated by DB DEFAULT gen_random_uuid()::text on INSERT,
// preserved on UPDATE. Read from the upsert-RETURNING row and returned
// to the client (so the CLP can build a magic-link handover button)
// as well as forwarded to Brevo as PORTAL_TOKEN attribute.
//
// 2026-05-20: background tasks (Slack hot-lead + Brevo contact upsert) are
// now wrapped in `EdgeRuntime.waitUntil(...)` so the Deno runtime keeps the
// worker alive until those promises settle. Without this wrapper Deno can
// (and does) kill the worker as soon as the Response is returned, causing
// silent drops of Brevo/Slack writes when the function returns faster than
// the third-party round-trip (observed: lead-upsert ~235ms, Brevo ~400ms).

import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'
import { createClient, SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4'
import { notifyHotLead, notifyNewLead, notifyError } from './slack.ts'
import { upsertBrevoContact } from './brevo.ts'
import { notifyZapierWalkin } from './zapier.ts'

// Supabase Edge Runtime global — declare here so TypeScript is happy.
// Falls back to a no-op `.then(...)` if the global is missing (e.g. local
// `deno run` outside Supabase), so the function never crashes.
declare const EdgeRuntime: { waitUntil: (p: Promise<unknown>) => void } | undefined

function keepAlive(promise: Promise<unknown>): void {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const er = (globalThis as any).EdgeRuntime as
    | { waitUntil: (p: Promise<unknown>) => void } | undefined
  if (er && typeof er.waitUntil === 'function') {
    er.waitUntil(promise)
  } else {
    // Local dev fallback: await it in the response path is too late, but at
    // least catch any rejection so it doesn't bubble as an unhandled error.
    promise.catch(() => {})
  }
}

const DEFAULT_ALLOWED = [
  // CLP-hostnames per project + lokale dev + Vercel preview
  'https://dehofman.clp.repp.nl',
  'https://depaveri.clp.repp.nl',
  'https://elster11.clp.repp.nl',
  'https://pier14.clp.repp.nl',
  'https://clp-xi-tan.vercel.app',
  'http://localhost:5173',
  'http://localhost:5174',
  'http://localhost:4173',
  // Portal (dehofman.nl + projectportal Vercel preview)
  'https://dehofman.nl',
  'https://www.dehofman.nl',
  'https://projectportal.vercel.app',
  'http://localhost:3000',
]

function corsAllowed(origin: string | null): string {
  // Defensief: ALLOWED_ORIGINS secret is ADDITIVE, niet vervangend.
  // Anders kan een misconfigured secret (missing dehofman.nl) silently de
  // Portal-CORS breken. DEFAULT_ALLOWED garandeert dat de bekende origins
  // ALTIJD werken; secret kan extra origins toevoegen (preview, custom).
  const fromEnv = (Deno.env.get('ALLOWED_ORIGINS') ?? '')
    .split(',').map(s => s.trim()).filter(Boolean)
  const list = Array.from(new Set([...DEFAULT_ALLOWED, ...fromEnv]))
  if (origin && list.includes(origin)) return origin
  return list[0] ?? '*'
}

function corsHeaders(origin: string | null): Record<string, string> {
  return {
    'Access-Control-Allow-Origin':  corsAllowed(origin),
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Max-Age':       '86400',
    'Vary':                         'Origin',
  }
}

interface ConsentEntry {
  scope: string
  granted: boolean
  privacy_statement_version?: string
  user_agent?: string
  detail?: Record<string, unknown>
}

interface LeadPayload {
  session_id:    string
  source:        string
  email?:        string | null
  first_name?:   string | null
  phone?:        string | null
  persona?:              string | null
  intent_id?:            string | null
  size_id?:              string | null
  timeline_id?:          string | null
  temperature?:          string | null
  score?:                number | null
  stage?:                string | null
  status?:               string | null
  cta_variant?:          string | null
  followup?:             string | null
  afhaak_reason?:        string | null
  handoff_shown?:        boolean | null
  handoff_outcome?:      string | null
  handoff_temperature?:  string | null
  handoff_persona?:      string | null
  started_at?:    string | null
  last_event_at?: string | null
  completed_at?:  string | null
  privacy_statement_version?: string | null
  attributes?: Record<string, unknown>
  consents?: ConsentEntry[]
}

function validate(payload: unknown): { ok: true; data: LeadPayload } | { ok: false; error: string } {
  if (!payload || typeof payload !== 'object') {
    return { ok: false, error: 'payload must be a JSON object' }
  }
  const p = payload as Record<string, unknown>
  if (typeof p.session_id !== 'string' || p.session_id.length < 8) {
    return { ok: false, error: 'session_id is required and must be >= 8 chars' }
  }
  if (typeof p.source !== 'string' || p.source.length === 0) {
    return { ok: false, error: 'source is required (e.g. "clp_dehofman")' }
  }
  if (p.score !== undefined && p.score !== null && typeof p.score !== 'number') {
    return { ok: false, error: 'score must be a number or null' }
  }
  if (p.consents !== undefined && !Array.isArray(p.consents)) {
    return { ok: false, error: 'consents must be an array' }
  }
  return { ok: true, data: p as LeadPayload }
}

interface UpsertLeadResult {
  id:           string | null
  portal_token: string | null
  isNew:        boolean
  error:        string | null
}

// Partial-unique index (CRM-dedup) op de leads-tabel:
//   UNIQUE (phone_normalized, project)
//   WHERE phone_normalized IS NOT NULL AND project IS NOT NULL
//         AND non_inbound_outbound_status IS NULL
// Dwingt max één ACTIEVE lead per telefoonnummer per project af.
//
// phone_normalized is een GENERATED ALWAYS-kolom (uit phone). Zodra een
// CLP-bezoeker een 06 invult dat al een actieve lead heeft in hetzelfde
// project (terugkerende bezoeker, of herhaalde test met hetzelfde nummer),
// botst de INSERT/UPDATE op deze index en faalde de hele functie met 500 —
// waardoor de lead NOCH in Supabase NOCH in Brevo landde.
const PHONE_DEDUP_CONSTRAINT = 'leads_phone_normalized_project_uniq'

// Detecteert exact de phone-dedup unique-violation (SQLSTATE 23505 op de
// bovenstaande index). Andere 23505's (bv. andere constraints) laten we
// gewoon als fout doorlopen — we verbreden de catch bewust niet.
function isPhoneDedupViolation(
  error: { code?: string; message?: string; details?: string } | null,
): boolean {
  if (!error || error.code !== '23505') return false
  const haystack = `${error.message ?? ''} ${error.details ?? ''}`
  return haystack.includes(PHONE_DEDUP_CONSTRAINT)
}

async function upsertLead(supa: SupabaseClient, p: LeadPayload): Promise<UpsertLeadResult> {
  // portal_token is INTENTIONALLY not in this row object. DB DEFAULT fills it
  // on INSERT, existing value preserved on UPDATE.
  //
  // project = source by design. DB-trigger leads_set_clp_project_from_source
  // mapt source→project alleen voor clp_* + dehofman_portal_* patterns en
  // mist nieuwe sources zoals "Paveri BUnit" (spatie + caps). Door 't hier
  // expliciet te zetten heeft de WA-bot-cron + gemini-followup altijd een
  // project-veld, ongeacht source-naamgeving van toekomstige projecten.
  const row: Record<string, unknown> = {
    session_id:    p.session_id,
    source:        p.source,
    project:       p.source,
    last_event_at: p.last_event_at ?? new Date().toISOString(),
  }

  const optional: Array<keyof LeadPayload> = [
    'email', 'first_name', 'phone',
    'persona', 'intent_id', 'size_id', 'timeline_id',
    'temperature', 'score', 'stage', 'status',
    'cta_variant', 'followup', 'afhaak_reason',
    'handoff_shown', 'handoff_outcome', 'handoff_temperature', 'handoff_persona',
    'started_at', 'completed_at',
    'privacy_statement_version',
    'attributes',
  ]
  for (const k of optional) {
    if (p[k] !== undefined) row[k] = p[k]
  }

  const writeRow = (r: Record<string, unknown>) =>
    supa
      .from('leads')
      .upsert(r, { onConflict: 'source,session_id', ignoreDuplicates: false })
      .select('id, portal_token')
      .single()

  let { data, error } = await writeRow(row)

  // Phone-dedup botsing: schrijf het duplicaat alsnog weg, maar gemarkeerd
  // als 'duplicate'. Die niet-lege status haalt de rij uit de partial-unique
  // index (WHERE ... non_inbound_outbound_status IS NULL) ÉN uit de outbound-
  // dispatcher-selectie (die uitsluitend status IS NULL / 'pending' pakt).
  //
  // Gevolg: de ORIGINELE actieve lead blijft volledig ongemoeid en houdt de
  // WhatsApp-opvolging; dit duplicaat is zichtbaar voor sales + wordt naar
  // Brevo ge-upsert (Brevo dedupt op email), maar krijgt géén eigen outbound.
  // Dat is identiek aan het bestaande dedup-gedrag — geen nieuw automation-
  // pad. Subsequente upserts in dezelfde sessie laten de 'duplicate'-status
  // ongemoeid (kolom zit niet in row), dus de rij blijft buiten de index.
  if (error && isPhoneDedupViolation(error as { code?: string; message?: string; details?: string })) {
    ;({ data, error } = await writeRow({ ...row, non_inbound_outbound_status: 'duplicate' }))
  }

  if (error) {
    return { id: null, portal_token: null, isNew: false, error: error.message }
  }
  const r = data as { id: string; portal_token: string | null }
  return { id: r.id, portal_token: r.portal_token ?? null, isNew: true, error: null }
}

async function appendConsents(
  supa: SupabaseClient,
  leadId: string | null,
  p: LeadPayload,
  userAgent: string,
): Promise<{ inserted: number; error: string | null }> {
  if (!p.consents || p.consents.length === 0) return { inserted: 0, error: null }

  const rows = p.consents.map(c => ({
    session_id: p.session_id,
    lead_id:    leadId,
    source:     p.source,
    scope:      c.scope,
    granted:    !!c.granted,
    privacy_statement_version:
      c.privacy_statement_version ?? p.privacy_statement_version ?? 'unknown',
    user_agent: (c.user_agent ?? userAgent ?? '').slice(0, 200),
    detail:     c.detail ?? {},
  }))

  const { error } = await supa.from('consent_log').insert(rows)
  if (error) return { inserted: 0, error: error.message }
  return { inserted: rows.length, error: null }
}

serve(async (req: Request) => {
  const origin = req.headers.get('origin')
  const cors   = corsHeaders(origin)

  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors })
  if (req.method !== 'POST')    return json({ error: 'method_not_allowed' }, 405, cors)

  let body: unknown
  try { body = await req.json() } catch { return json({ error: 'bad_json' }, 400, cors) }

  const v = validate(body)
  if (!v.ok) return json({ error: 'validation_failed', detail: v.error }, 400, cors)

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL')
  const SERVICE_KEY  = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
  if (!SUPABASE_URL || !SERVICE_KEY) return json({ error: 'server_misconfigured' }, 500, cors)

  const supa = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  })

  const ua = req.headers.get('user-agent') ?? ''

  // Snapshot van het bestaande lead-record (indien aanwezig) zodat we
  // post-upsert kunnen detecteren of dit de eerste keer is dat email
  // wordt gezet. Zo voorkomen we dat we bij elke state-update een
  // Slack-bericht spammen naar #generation. SELECT is goedkoop: gedekt
  // door de unique-index op (source, session_id).
  const { data: existingRow } = await supa
    .from('leads')
    .select('email')
    .eq('source', v.data.source)
    .eq('session_id', v.data.session_id)
    .maybeSingle()
  const existingEmail = (existingRow as { email: string | null } | null)?.email ?? null

  const lead = await upsertLead(supa, v.data)
  if (lead.error) {
    // Kritiek: lead-data is hier nog niet weggeschreven. Sales moet
    // dit weten zodat ze de bezoeker handmatig kunnen terugbellen.
    keepAlive(notifyError('lead_upsert_failed (Supabase DB write)', {
      source: v.data.source,
      email: v.data.email,
      first_name: v.data.first_name,
      phone: v.data.phone,
      detail: lead.error,
    }))
    return json({ error: 'lead_upsert_failed', detail: lead.error }, 500, cors)
  }

  const cons = await appendConsents(supa, lead.id, v.data, ua)
  if (cons.error) {
    return json(
      { ok: true, lead_id: lead.id, portal_token: lead.portal_token, consent_error: cons.error, consents_inserted: 0 },
      207, cors,
    )
  }

  // Slack-notificatie naar #generation kanaal bij eerste email-capture.
  // Conditie: bestaande row had geen email + nieuwe payload heeft wel
  // email. Fired ÉÉN keer per lead, ongeacht source (CLP, portal walk-in,
  // exit-intent — alles waar email voor het eerst binnen komt).
  const isFirstEmailCapture = !existingEmail && !!v.data.email
  if (isFirstEmailCapture) {
    keepAlive(
      notifyNewLead(v.data, lead.id).catch((err) => {
        console.error('[slack] notifyNewLead failed', err)
      }),
    )
  }

  if (v.data.temperature === 'hot') {
    keepAlive(
      notifyHotLead(v.data, lead.id).catch((err) => {
        console.error('[slack] notifyHotLead failed', err)
      }),
    )
  }

  // Brevo + Zapier hebben hun eigen notifyError-paden inline (in brevo.ts
  // en zapier.ts). Hier alleen nog last-resort console.error voor unhandled
  // throws die buiten hun internal catch ontsnappen.
  keepAlive(
    upsertBrevoContact(
      { ...v.data, portal_token: lead.portal_token },
      lead.id,
    ).catch((err) => console.error('[brevo] upsertBrevoContact threw', err)),
  )

  // Zapier walk-in webhook — alleen voor dehofman_portal_* sources.
  // CLP-leads gaan via Slack + Brevo, dus niet dubbel via Zapier.
  keepAlive(
    notifyZapierWalkin(
      { ...v.data, portal_token: lead.portal_token },
      lead.id,
    ).catch((err) => console.error('[zapier] notifyZapierWalkin threw', err)),
  )

  return json(
    { ok: true, lead_id: lead.id, portal_token: lead.portal_token, consents_inserted: cons.inserted },
    200, cors,
  )
})

function json(payload: unknown, status: number, cors: Record<string, string>): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...cors, 'Content-Type': 'application/json' },
  })
}
