// Edge Function: lead-upsert
// Runtime:  Supabase Edge (Deno)
// Purpose:  Single write-path for CLP leads + consent. Service-role-key lives
//           here (server-side env vars), never in the browser bundle.
//
// Endpoint shape:
//   POST  https://<project>.supabase.co/functions/v1/lead-upsert
//   Headers:
//     Content-Type: application/json
//     Authorization: Bearer <SUPABASE_ANON_KEY>
//   Body:
//     { "session_id": "...", "source": "clp_dehofman", ...lead fields,
//       "consents": [{ "scope": "...", "granted": true, "detail": {...} }] }
//
// Response: { ok: true, lead_id, portal_token, consents_inserted }
//
// Portal token: generated by DB DEFAULT gen_random_uuid()::text on INSERT,
// preserved on UPDATE. Read from the upsert-RETURNING row and returned
// to the client (so the CLP can build a magic-link handover button)
// as well as forwarded to Brevo as PORTAL_TOKEN attribute.
//
// 2026-05-20: background tasks (Slack hot-lead + Brevo contact upsert) are
// now wrapped in `EdgeRuntime.waitUntil(...)` so the Deno runtime keeps the
// worker alive until those promises settle. Without this wrapper Deno can
// (and does) kill the worker as soon as the Response is returned, causing
// silent drops of Brevo/Slack writes when the function returns faster than
// the third-party round-trip (observed: lead-upsert ~235ms, Brevo ~400ms).

import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'
import { createClient, SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4'
import { notifyHotLead } from './slack.ts'
import { upsertBrevoContact } from './brevo.ts'

// Supabase Edge Runtime global — declare here so TypeScript is happy.
// Falls back to a no-op `.then(...)` if the global is missing (e.g. local
// `deno run` outside Supabase), so the function never crashes.
declare const EdgeRuntime: { waitUntil: (p: Promise<unknown>) => void } | undefined

function keepAlive(promise: Promise<unknown>): void {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const er = (globalThis as any).EdgeRuntime as
    | { waitUntil: (p: Promise<unknown>) => void } | undefined
  if (er && typeof er.waitUntil === 'function') {
    er.waitUntil(promise)
  } else {
    // Local dev fallback: await it in the response path is too late, but at
    // least catch any rejection so it doesn't bubble as an unhandled error.
    promise.catch(() => {})
  }
}

const DEFAULT_ALLOWED = [
  'https://dehofman.clp.repp.nl',
  'https://clp-xi-tan.vercel.app',
  'http://localhost:5173',
  'http://localhost:4173',
]

function corsAllowed(origin: string | null): string {
  const list = (Deno.env.get('ALLOWED_ORIGINS') ?? DEFAULT_ALLOWED.join(','))
    .split(',').map(s => s.trim()).filter(Boolean)
  if (origin && list.includes(origin)) return origin
  return list[0] ?? '*'
}

function corsHeaders(origin: string | null): Record<string, string> {
  return {
    'Access-Control-Allow-Origin':  corsAllowed(origin),
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Max-Age':       '86400',
    'Vary':                         'Origin',
  }
}

interface ConsentEntry {
  scope: string
  granted: boolean
  privacy_statement_version?: string
  user_agent?: string
  detail?: Record<string, unknown>
}

interface LeadPayload {
  session_id:    string
  source:        string
  email?:        string | null
  first_name?:   string | null
  phone?:        string | null
  persona?:              string | null
  intent_id?:            string | null
  size_id?:              string | null
  timeline_id?:          string | null
  temperature?:          string | null
  score?:                number | null
  stage?:                string | null
  status?:               string | null
  cta_variant?:          string | null
  followup?:             string | null
  afhaak_reason?:        string | null
  handoff_shown?:        boolean | null
  handoff_outcome?:      string | null
  handoff_temperature?:  string | null
  handoff_persona?:      string | null
  started_at?:    string | null
  last_event_at?: string | null
  completed_at?:  string | null
  privacy_statement_version?: string | null
  attributes?: Record<string, unknown>
  consents?: ConsentEntry[]
}

function validate(payload: unknown): { ok: true; data: LeadPayload } | { ok: false; error: string } {
  if (!payload || typeof payload !== 'object') {
    return { ok: false, error: 'payload must be a JSON object' }
  }
  const p = payload as Record<string, unknown>
  if (typeof p.session_id !== 'string' || p.session_id.length < 8) {
    return { ok: false, error: 'session_id is required and must be >= 8 chars' }
  }
  if (typeof p.source !== 'string' || p.source.length === 0) {
    return { ok: false, error: 'source is required (e.g. "clp_dehofman")' }
  }
  if (p.score !== undefined && p.score !== null && typeof p.score !== 'number') {
    return { ok: false, error: 'score must be a number or null' }
  }
  if (p.consents !== undefined && !Array.isArray(p.consents)) {
    return { ok: false, error: 'consents must be an array' }
  }
  return { ok: true, data: p as LeadPayload }
}

interface UpsertLeadResult {
  id:           string | null
  portal_token: string | null
  isNew:        boolean
  error:        string | null
}

async function upsertLead(supa: SupabaseClient, p: LeadPayload): Promise<UpsertLeadResult> {
  // portal_token is INTENTIONALLY not in this row object. DB DEFAULT fills it
  // on INSERT, existing value preserved on UPDATE.
  const row: Record<string, unknown> = {
    session_id:    p.session_id,
    source:        p.source,
    last_event_at: p.last_event_at ?? new Date().toISOString(),
  }

  const optional: Array<keyof LeadPayload> = [
    'email', 'first_name', 'phone',
    'persona', 'intent_id', 'size_id', 'timeline_id',
    'temperature', 'score', 'stage', 'status',
    'cta_variant', 'followup', 'afhaak_reason',
    'handoff_shown', 'handoff_outcome', 'handoff_temperature', 'handoff_persona',
    'started_at', 'completed_at',
    'privacy_statement_version',
    'attributes',
  ]
  for (const k of optional) {
    if (p[k] !== undefined) row[k] = p[k]
  }

  const { data, error } = await supa
    .from('leads')
    .upsert(row, { onConflict: 'source,session_id', ignoreDuplicates: false })
    .select('id, portal_token')
    .single()

  if (error) {
    return { id: null, portal_token: null, isNew: false, error: error.message }
  }
  const r = data as { id: string; portal_token: string | null }
  return { id: r.id, portal_token: r.portal_token ?? null, isNew: true, error: null }
}

async function appendConsents(
  supa: SupabaseClient,
  leadId: string | null,
  p: LeadPayload,
  userAgent: string,
): Promise<{ inserted: number; error: string | null }> {
  if (!p.consents || p.consents.length === 0) return { inserted: 0, error: null }

  const rows = p.consents.map(c => ({
    session_id: p.session_id,
    lead_id:    leadId,
    source:     p.source,
    scope:      c.scope,
    granted:    !!c.granted,
    privacy_statement_version:
      c.privacy_statement_version ?? p.privacy_statement_version ?? 'unknown',
    user_agent: (c.user_agent ?? userAgent ?? '').slice(0, 200),
    detail:     c.detail ?? {},
  }))

  const { error } = await supa.from('consent_log').insert(rows)
  if (error) return { inserted: 0, error: error.message }
  return { inserted: rows.length, error: null }
}

serve(async (req: Request) => {
  const origin = req.headers.get('origin')
  const cors   = corsHeaders(origin)

  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors })
  if (req.method !== 'POST')    return json({ error: 'method_not_allowed' }, 405, cors)

  let body: unknown
  try { body = await req.json() } catch { return json({ error: 'bad_json' }, 400, cors) }

  const v = validate(body)
  if (!v.ok) return json({ error: 'validation_failed', detail: v.error }, 400, cors)

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL')
  const SERVICE_KEY  = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
  if (!SUPABASE_URL || !SERVICE_KEY) return json({ error: 'server_misconfigured' }, 500, cors)

  const supa = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  })

  const ua = req.headers.get('user-agent') ?? ''

  const lead = await upsertLead(supa, v.data)
  if (lead.error) return json({ error: 'lead_upsert_failed', detail: lead.error }, 500, cors)

  const cons = await appendConsents(supa, lead.id, v.data, ua)
  if (cons.error) {
    return json(
      { ok: true, lead_id: lead.id, portal_token: lead.portal_token, consent_error: cons.error, consents_inserted: 0 },
      207, cors,
    )
  }

  if (v.data.temperature === 'hot') {
    keepAlive(
      notifyHotLead(v.data, lead.id).catch((err) => {
        console.error('[slack] notifyHotLead failed', err)
      }),
    )
  }

  keepAlive(
    upsertBrevoContact({ ...v.data, portal_token: lead.portal_token }).catch((err) => {
      console.error('[brevo] upsertBrevoContact failed', err)
    }),
  )

  return json(
    { ok: true, lead_id: lead.id, portal_token: lead.portal_token, consents_inserted: cons.inserted },
    200, cors,
  )
})

function json(payload: unknown, status: number, cors: Record<string, string>): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...cors, 'Content-Type': 'application/json' },
  })
}
